version: '3.8'

services:
  # PostgreSQL
  postgres:
    image: postgres:17-alpine
    container_name: enderr-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: enderr
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Local DynamoDB
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - '8000:8000'
    command: '-jar DynamoDBLocal.jar -sharedDb'
    working_dir: /home/dynamodblocal
    environment:
      # These are ignored by DynamoDB Local but included for documentation
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_REGION=local
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

  # DynamoDB Admin UI (optional but helpful for development)
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    ports:
      - '8001:8001'
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=local
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    depends_on:
      - dynamodb-local

volumes:
  postgres_data:
  dynamodb_data:
