# DynamoDB table definition for storing today's schedules
# This is part of AWS CloudFormation/Serverless Framework template
TodaySchedulesTable:
  # Defines this as a DynamoDB table resource in AWS CloudFormation
  Type: AWS::DynamoDB::Table
  Properties:
    # Table name is defined in serverless.yml custom variables
    # Example: ${self:custom.todaySchedulesTable} might resolve to "prod-today-schedules"
    TableName: ${self:custom.todaySchedulesTable}

    # PAY_PER_REQUEST means you only pay for actual usage (on-demand pricing)
    # Alternative: PROVISIONED - requires setting ReadCapacityUnits and WriteCapacityUnits
    BillingMode: PAY_PER_REQUEST

    # Define the data types of attributes used in key schema and indexes
    # Only attributes used as keys need to be defined here
    AttributeDefinitions:
      # Primary partition key
      - AttributeName: pk # Example value: "user#123#date#2024-03-20"
        AttributeType: S # S = String type
      # Primary sort key
      - AttributeName: sk # Example value: "time#0900#schedule#456"
        AttributeType: S
      # GSI partition key
      - AttributeName: GSI1PK # Example value: "status#active"
        AttributeType: S
      # GSI sort key
      - AttributeName: GSI1SK # Example value: "time#0900"
        AttributeType: S

    # Define the primary key structure
    KeySchema:
      # HASH is the partition key - used to distribute data across partitions
      - AttributeName: pk
        KeyType: HASH
      # RANGE is the sort key - used to sort items within a partition
      - AttributeName: sk
        KeyType: RANGE

    # Global Secondary Indexes (GSI) allow querying using different partition/sort keys
    GlobalSecondaryIndexes:
      - IndexName: GSI1 # Can be queried using GSI1PK and GSI1SK
        KeySchema:
          - AttributeName: GSI1PK
            KeyType: HASH
          - AttributeName: GSI1SK
            KeyType: RANGE
        # ProjectionType: ALL means all attributes are copied to the index
        # Alternatives:
        # - KEYS_ONLY: only key attributes
        # - INCLUDE: specify attributes to include
        Projection:
          ProjectionType: ALL

    # TTL (Time To Live) configuration
    # DynamoDB will automatically delete items when current time > expiresAt
    TimeToLiveSpecification:
      AttributeName: expiresAt # Unix timestamp when item should be deleted
      Enabled: true
# Access Patterns this table design supports:
# 1. Get all schedules for a user for today:
#    - Query by pk = "user#123#date#2024-03-20"
# 2. Get schedules within a time range:
#    - Query by pk and sk between "time#0900" and "time#1700"
# 3. Get all active schedules by time (using GSI1):
#    - Query GSI1 with GSI1PK = "status#active"
#    - Results will be sorted by time (GSI1SK)
